Typing identdefs
disruptek/cps pull request #144
Opened 2021-05-31 02:39 UTC by saem

2021-05-31 04:55 UTC, disruptek requested changes
really great job.  except for var/let section.  but if we can solve identdefs this way it is massive.

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +  result.rs = newIdentDefs("result", rs)
i don't get it.  surely the more elaborately complete and send-documenting version is more ideal, right?

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +  doAssert kind in {nnkVarSection, nnkLetSection, nnkIdentDefs}
just remove it; we intend to solve these problems with proper typing.

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +  case n.typ.kind:
now we're talkin'.

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +      newVarSection(e.ex, nnkRefTy.newTree(bindSym"Exception"), newNilLit())
ah, i see what you did there.  clever.

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +  elif env.rs.hasType:
hello again, my friend.

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +  VarSection* = distinct NormalizedNimNode
omg you may have nailed it.

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +  doAssert n.kind == nnkIdentDefs, "not and IdentDefs, got: " & $n.kind
not an IdentDefs

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +nimNodeConverter(IdentDefs)
but really it's a converterToNimNode, right?

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +  newIdentDefs(ident(n), info, val).IdentDefs
ah, good.

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +  n.val.kind != nnkEmpty
maybe hasValue since it's also hasType.

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +proc newVarSection*(i: IdentDefs): VarSection =
Yes but no because we want to distinguish between identdefs that are mutable versus those that are immutable.  That information can help us optimize ourselves and also let's us put a spin on the output -- _not just an identdefs, but an immutable one_.

2021-05-31 04:55 UTC, disruptek commented on cps/normalizedast.nim
> +proc addPragma*(n: ProcDef, prag: NimNode, pragArg: NimNode) =
very good.

2021-05-31 04:55 UTC, disruptek commented on cps/transform.nim
> +  booty.addPragma(bindSym"cpsBootstrap", whelp.name)
yes.

2021-05-31 04:55 UTC, disruptek commented on cps/transform.nim
> +  n.addPragma(bindSym"cpsResolver", env.identity)
yes.

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +    cVarSectionToNimNode(newVarSection(c, env.root))
but why?

2021-05-31 04:55 UTC, disruptek commented on cps/environment.nim
> +  result.rs = newIdentDefs("result", rs)
_narrator: it wasn't._

2021-05-31 04:55 UTC, disruptek commented on cps/transform.nim
> +  n.addPragma(bindSym"cpsResolver", env.identity)
there's a bracket form, too, right?  maybe via openArray?

2021-05-31 04:57 UTC, disruptek commented
also, is there an iterator for identdefs already?  and how about tuples?  works?

2021-05-31 05:26 UTC, saem commented on cps/environment.nim
> +  set(e, key, cVarSectionToNimNode(val))
If I don't put it here, it'll keep calling itself over and over again and crap out the transform.

2021-05-31 05:27 UTC, saem commented on cps/environment.nim
> +    e = e.set(e.rs.name, newVarSection e.rs)
yeah, that part could be better, need a fancier type to unify all this stuff.

2021-05-31 05:33 UTC, saem commented on cps/environment.nim
> +proc set(e: var Env; key: NimNode; val: VarSection): Env
I want to get to key typed but it'll take a few successive transforms to get to the right signature.

2021-05-31 05:43 UTC, saem commented on cps/environment.nim
> +  result.rs = newIdentDefs("result", rs)
* `newIdentDefs("result", info = rs)` sucks less?
* `newResultIdentDefs(info = rs)`, sucks less ...

Wait, did that last example just pointed out that this isn't an `IdentDefs` because it's not normalized (no type and no val)?

2021-05-31 05:45 UTC, saem commented on cps/environment.nim
> +  doAssert kind in {nnkVarSection, nnkLetSection, nnkIdentDefs}
I need this temporarily, but yeah it needs to go longer term.

This is how I figured out the lesson about all the various forms of `IdentDefs` and how I probably will have to evolve the types a bunch more.

2021-05-31 05:48 UTC, saem commented on cps/environment.nim
> +      newVarSection(e.ex, nnkRefTy.newTree(bindSym"Exception"), newNilLit())
This was the other thing making me suspect I don't think we really want to be making straight `IdentDefs`, we likely want to emit VarSection, LetSection, ProcDefArg, GenericParamDef, etc... or at least have constructors that do the whole production cleanly without denormalization concerns outside of that.

2021-05-31 05:48 UTC, saem commented on cps/normalizedast.nim
> +  doAssert n.kind == nnkIdentDefs, "not and IdentDefs, got: " & $n.kind
I'd burn this PR just on this alone.

2021-05-31 05:51 UTC, saem commented on cps/normalizedast.nim
> +nimNodeConverter(IdentDefs)
No, I hate it, they're wrong. I'm only tolerating them because the `.NimNode` spam would be high, but as things become more typed we should throw them out ASAP and put in the spam in the few places where it ends up being a forcing function for the type conversion.

2021-05-31 05:53 UTC, saem commented on cps/normalizedast.nim
> +proc newVarSection*(i: IdentDefs): VarSection =
Daaaayum, that's a whole different level, so you're thinking:
* pre-normalization <-- we don't type this shit
* post-normalization <-- what we're typing and is mutable
* post-transform <-- this is what you're talking about and it's immutable

Did I get that right?

2021-05-31 05:54 UTC, saem commented on cps/normalizedast.nim
> +  n.val.kind != nnkEmpty
yeah, I was flip flopping on that one, `hasValue` it is.

Yes, proc, you ARE a good proc. You have value, hasValue, in fact.

2021-05-31 05:59 UTC, saem commented on cps/environment.nim
> +    cVarSectionToNimNode(newVarSection(c, env.root))
it calls the wrong add if I don't force it... because "converters" work so well. 🙄

2021-05-31 06:05 UTC, saem commented
There is not an iterator for identdefs, but that's a bit of a can of worms:
* in what situations do you want to iterate over identdefs
* are we talking about procdef params, generic param defs, var/let section runs?
* or in some other general sense?
* because normalizingRewrites is a lot better/regular, reasons to iterate over identdefs are dying I think

Tuples and LetSections can be next on the hit list, that should collapse a bunch more environment code.

2021-05-31 06:06 UTC, saem commented on cps/transform.nim
> +  n.addPragma(bindSym"cpsResolver", env.identity)
Good idea, I'll add a reminder and if we need it then we can pop that in.

2021-05-31 07:09 UTC, disruptek commented on cps/environment.nim
> +  result.rs = newIdentDefs("result", rs)
no, i came around on this one.

2021-05-31 07:12 UTC, disruptek commented on cps/normalizedast.nim
> +nimNodeConverter(IdentDefs)
How is it a forcing function?  It's forcing me to write more than I need to.  If you're a person that buys NimNodes and I offer to sell you an IdentDefs, you are getting more than you paid for, clearly.  So why shouldn't that converter exist?  It makes money every time it's used!

2021-05-31 07:16 UTC, disruptek commented on cps/normalizedast.nim
> +proc newVarSection*(i: IdentDefs): VarSection =
You're right that post-transform it's immutable, yes.  What we structure in a var section to signal mutability is:
- var sections
- proc params that are vars
Everything else is immutable:
- let sections
- proc params that are not vars

2021-05-31 07:48 UTC, saem commented on cps/normalizedast.nim
> +nimNodeConverter(IdentDefs)
Because you shouldn't need to sell identdefs, rather we want to get rid on the NimNode buyers as much as possible.

So by forcing us to write it out in the meantime the ugliness encourages typing harder to make the ugly go away.

If we think about why we need say a procdef to NimNode converter. Only reason it should exist is to add in a transformed procdef to the module, float a procdef, or add an inner proc. That's what one or two call sites at most? Whereas we don't need all the macros helpers which are invariant breaking "features" waiting to happen.

2021-05-31 15:30 UTC, saem commented on cps/environment.nim
> +  result.rs = newIdentDefs("result", rs)
I know, but maybe babes is hiding here oh well, future us problem.

2021-05-31 15:38 UTC, saem commented on cps/normalizedast.nim
> +proc newVarSection*(i: IdentDefs): VarSection =
Ok so this is for later me thinks.

2021-06-01 00:19 UTC, alaviss reviewed
looks fine otherwise, great work @saem

2021-06-01 00:19 UTC, alaviss commented on cps/normalizedast.nim
> +proc newIdentDefs*(n: string, info: NimNode, val = newEmptyNode()): IdentDefs =
```suggestion
proc newIdentDefs*(n: string, typ: NimNode, val = newEmptyNode()): IdentDefs =
```

We typically use `info` for lineinfo, not types

2021-06-01 13:11 UTC, merged