cps/transform: implement a context management system for exception
disruptek/cps pull request #175
Opened 2021-06-17 02:55 UTC by alaviss

Exception handlers in Nim operates on a stack built within the Exception
object. Thus to ensure that continuations don't corrupt the stack
outside of CPS, we generates a manager that configures the current exception
to the continuation's before running the continuation, then restore the
original on return.

Known issue:
- Clearing the exception in the continuation is not reimplemented yet
- We are still ignoring unhandled exceptions coming from the continuation

2021-06-17 03:28 UTC, disruptek commented
Suggestion: use `genAst` for the body code at the end of `withException`.

2021-06-18 02:21 UTC, disruptek requested changes
I still like the approach; never had a problem with the logic.

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +        result.params[1][0] = desym result.params[1][0]
We still can't do this without indexing?  :roll_eyes:

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +        {.warning: "Compiler bug walkaround".}
still `workaround`.  the idea is that you have to do work that you shouldn't have to do via the more direct route.

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +                                            it[0] == bindSym"cpsHasException")
if we cannot use `hasPragma`, we need something here that we _can_ use.

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +      if hasException != nil:
prefer `isNil`

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +        let inner = n.ProcDef.clone(n.body)
prefer `clone(n.ProcDef, body = n.body)`

more of these follow...  we want to emphasize the verb, then the noun.

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +          ex = hasException[2].resym(exCont, cont)
Why don't we unpack these when we first establish `hasException` so I can remember what the hell this stuff means.  It needs a comment in any event.

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +          ex[0][1] = cont
You may as well not bother with the `if`, right?

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +              raise e
What did you think of `genAst` here?

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +      # Rewrites the inner continuations too
```suggestion
      # Rewrite the inner continuations, too.
```

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +  doAssert cont == ex[0][1]
Lazy.  Not a fan.  :wink:

2021-06-18 02:21 UTC, disruptek commented on cps/transform.nim
> +  filter(n, marker)
Prefer an explicit result assignment this low on the page.

2021-06-18 15:21 UTC, alaviss commented on cps/transform.nim
> +                                            it[0] == bindSym"cpsHasException")
Need @Clyybber's `getPragma`

2021-06-18 16:40 UTC, alaviss commented on cps/transform.nim
> +              raise e
It works, the capture interface is terrible IMO.

Also there's a bug with emitting result so you must use `result = ident"result"`.

2021-06-19 14:33 UTC, merged