`...` and shim hack for simple cps call results
disruptek/cps pull request #180
Opened 2021-06-20 18:48 UTC by disruptek

2021-06-21 16:11 UTC, alaviss requested changes
Need a test where the child is dismissed, and documentation for the breaking change of `whelp` (returns `Env` instead of `Cont`).

2021-06-21 16:11 UTC, alaviss commented on cps/transform.nim
> +                  c = c.fn(c)
Can't we just `tramp` it?

Also it looks to me that this will definitely error out when `c` got dismissed, which doesn't sound very reasonable.

2021-06-21 16:24 UTC, disruptek commented on cps/transform.nim
> +                  c = c.fn(c)
Why wouldn't it error out?

And, we need to reproduce the trampoline so that `annotate` will convert it into continuation legs; otherwise, it's no longer a continuation!

2021-06-21 16:53 UTC, alaviss commented on cps/transform.nim
> +                  c = c.fn(c)
> Why wouldn't it error out?

Because if you call a `foo()` that doesn't return anything, then it can be dismissed however and it doesn't matter, after `foo()` completes it returns to `mom`.

Now if you call a `bar()` that returns something, then suddenly it errors out when `bar()` got dispatched elsewhere.

> And, we need to reproduce the trampoline so that annotate will convert it into continuation legs; otherwise, it's no longer a continuation!

wdym?

2021-06-25 19:28 UTC, alaviss commented on cps/environment.nim
> +      proc `...`(c: cont): tipe {.used.} =
Maybe we can always export this. The only way to use it is to have the Env type, which can only be obtained if the originating proc is exported.

2021-06-25 23:04 UTC, alaviss commented on cps/environment.nim
> +      proc `...`(c: cont): tipe {.used.} =
On an another thought, maybe not, as it will make cps incompatible for use with procs not on top-level.

2021-06-25 23:24 UTC, disruptek commented on cps/environment.nim
> +      proc `...`(c: cont): tipe {.used.} =
I don't think we can successfully export it in any event, so we're safe from having to worry about it.

2021-06-26 03:45 UTC, merged