cps, cps/environment: only desym environment access
disruptek/cps pull request #73
Opened 2021-04-26 05:33 UTC by alaviss

Experiments shows that we only have to desym due to issues in
environment definition and access.

Upstream bug: nim-lang/Nim#17851

Has #72 bundled.

2021-04-26 14:57 UTC, alaviss commented on cps.nim
> +        result.add newChild
I needed it to pass tests :P Was waiting for #72 to be merged so I can rebase

2021-04-26 14:59 UTC, alaviss commented on cps.nim
> +        except:
It has to be done because of env conversion being desym-ed. This is more of a hack IMO.

2021-04-27 03:44 UTC, alaviss commented
I'll need a bit of help to clean this up, the desym insertions is a hack atm, not to mention error prone. IMO we can build a kind of filter that desym any usage of a genSym-ed identifier from `Env`, but not sure if it's feasible.

2021-04-27 12:30 UTC, disruptek commented
Gensym'd symbols have names that don't match their `repr`.  That's enough to identify them for purposes of another rewrite, but usages of `Env` symbols can be filtered more easily -- either do something special once, when they are inserted into the in-memory cache of locals, or do something special N times when they are plucked out.

2021-04-28 13:44 UTC, alaviss commented
It's working now, and it's beautiful.

2021-04-28 14:04 UTC, disruptek requested changes
Nice; I like executing less code. :+1:

2021-04-28 14:04 UTC, disruptek commented on cps/spec.nim
> +  ## made as a walkaround for [nim-lang/Nim#17851](https://github.com/nim-lang/Nim/issues/17851)
s/walkaround/workaround/

2021-04-28 14:04 UTC, disruptek commented on cps/spec.nim
> +  ## made as a walkaround for [nim-lang/Nim#17851](https://github.com/nim-lang/Nim/issues/17851)
Also, `a unique`.

2021-04-28 14:57 UTC, saem approved these changes
This is a lot better. \o/

2021-04-28 14:57 UTC, saem commented on cps.nim
>        assert false, "unknown node type: " & $result.kind
Raising an error should be the job of whatever is calling this proc, imo. So the updated logic makes more sense.

2021-04-28 14:57 UTC, saem commented on cps.nim
> +  # No longer necessary as we are desym-ing on a selective basis
Why bother keeping it around?

2021-04-28 16:23 UTC, disruptek commented on cps.nim
>        assert false, "unknown node type: " & $result.kind
Yes, but then we `assert false` in the last leg...

2021-04-28 16:25 UTC, disruptek commented on cps.nim
> +  # No longer necessary as we are desym-ing on a selective basis
It's useful historical matter.  Not just that we used to do a thing, but _where_ we used to do that thing.  But, yeah, like I said in another comment, it can go if you prefer.

2021-04-28 16:44 UTC, disruptek commented on cps.nim
>        assert false, "unknown node type: " & $result.kind
In fact, it's an infinite loop without assertions to crash it.  Suggest you rewrite the `case` as `if/if/else` or whatever.  All three of us missed it the first time around.

2021-04-28 18:01 UTC, saem commented on cps.nim
>        assert false, "unknown node type: " & $result.kind
Hmm, your right, I changed it up to during debug that's probably a smell, but probably fine.

2021-04-28 18:39 UTC, disruptek commented on cps.nim
>        assert false, "unknown node type: " & $result.kind
That sounds fine to me. :+1:

2021-04-28 22:54 UTC, merged